/** Pure functions for generating handoff documents and prompts. No side effects. */

import type { Message, Mode } from '../shared-types';

export interface HandoffContext {
  conversationId: string;
  projectId: string;
  projectName: string;
  messages: Message[];
  orchestratorMode: Mode;
  currentGoal: string;
  whatWasTried: string[];
  whatWorked: string[];
  whatFailed: string[];
  pendingBugs: string[];
  nextStep: string;
  warnings: string[];
  idiosyncrasies: string;
  timestamp: string;
  isSelfMaintenance?: boolean;
  vibeFlowRepoPath?: string;
}

export interface HandoffArtifacts {
  handoffDoc: string;
  handoffPrompt: string;
  filename: string;
}

export function generateHandoffDoc(ctx: HandoffContext): string {
  const date = new Date(ctx.timestamp).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
  });

  const title = ctx.isSelfMaintenance
    ? `# 🔧 VibeFlow Self-Maintenance Handoff — ${date}`
    : `# Handoff — ${ctx.projectName} — ${date}`;

  return `${title}

## What We Are Trying to Do Right Now
${ctx.currentGoal}

## What We Have Tried
${ctx.whatWasTried.map(t => `- ${t}`).join('\n') || '- Nothing yet'}

## What Failed and Why
${ctx.whatFailed.map(f => `- ${f}`).join('\n') || '- No failures recorded'}

## What Worked
${ctx.whatWorked.map(w => `- ${w}`).join('\n') || '- Nothing recorded yet'}

## Current Architecture Summary
See /docs/architecture.md for the full technical architecture.

Key points:
- Electron desktop app (Windows-first)
- Supabase for cloud sync (Auth + Postgres + Realtime + Storage)
- OpenRouter for AI (primary provider)
- pnpm monorepo with apps/desktop and packages/*
- All shared code in apps/desktop/src/lib/ (no workspace symlinks — exFAT drive)
- electron.vite.config.ts (NOT vite.config.ts — see idiosyncrasies)

## Docs to Read First
1. /AGENTS.md — AI agent rules for this repo
2. /PROJECT_SOUL.md — Product vision and non-negotiables
3. /CURRENT_TASK.md — Current sprint and step
4. /docs/architecture.md — Full technical architecture
5. /docs/idiosyncrasies.md — Intentional weirdness (READ THIS)
6. /docs/decisions.md — Why key decisions were made

## Current Context
- Project: ${ctx.projectName}
- Conversation ID: ${ctx.conversationId}

## Known Oddities
See /docs/idiosyncrasies.md for the full list.

Key oddities:
- electron.vite.config.ts (not vite.config.ts) — electron-vite requires this exact name
- ELECTRON_RUN_AS_NODE env var must NOT be set — it breaks Electron
- No workspace:* deps — D: drive is exFAT, cannot symlink
- GitHub OAuth uses localhost redirect (temp HTTP server on port 54321-54323)

## Pending Bugs
${ctx.pendingBugs.map(b => `- ${b}`).join('\n') || '- None recorded'}

## Next Recommended Step
${ctx.nextStep}

## Important Warnings for a New AI Session
${ctx.warnings.map(w => `- ${w}`).join('\n') || '- None'}

---
*Generated by VibeFlow Handoff System at ${ctx.timestamp}*
`;
}

export function generateHandoffPrompt(ctx: HandoffContext): string {
  const selfMaintenanceWarning = ctx.isSelfMaintenance
    ? `
## ⚠️ SELF-MAINTENANCE MODE
You are working on the VibeFlow IDE itself. Be careful — mistakes can break the IDE.
VibeFlow repo path: ${ctx.vibeFlowRepoPath ?? 'unknown'}
All file changes to VibeFlow source files require human approval (Tier 3).
`
    : '';

  return `# VibeFlow Handoff Prompt

You are continuing work on the VibeFlow project. Read these files FIRST before doing anything:

1. /AGENTS.md
2. /PROJECT_SOUL.md
3. /CURRENT_TASK.md
4. /docs/idiosyncrasies.md (IMPORTANT — read this before touching any code)
5. /docs/architecture.md

## Current Task
${ctx.currentGoal}

## Next Step
${ctx.nextStep}

## Critical Warnings
${ctx.warnings.map(w => `- ${w}`).join('\n') || '- None'}${selfMaintenanceWarning}
## Key Facts
- This is a Windows-first Electron desktop app
- Use electron.vite.config.ts (NOT vite.config.ts)
- Do NOT set ELECTRON_RUN_AS_NODE
- No workspace:* deps (exFAT drive, no symlinks)
- All shared code lives in apps/desktop/src/lib/
- Run with: pnpm dev (from repo root)
- If ELECTRON_RUN_AS_NODE is set, run: Remove-Item Env:ELECTRON_RUN_AS_NODE first

## Full Handoff Document
See the handoff document in Supabase Storage for complete context.

---
*Project: ${ctx.projectName} | Generated: ${ctx.timestamp}*
`;
}
