/**
 * Injects build metadata into packages/build-metadata/src/generated.ts
 * Reads version from root package.json, git commit SHA and date, RELEASE_CHANNEL env var.
 */

import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

const rootDir = path.resolve(__dirname, '..');
const generatedPath = path.resolve(rootDir, 'packages/build-metadata/src/generated.ts');

function getGitCommitSha(): string {
  try {
    return execSync('git rev-parse --short HEAD').toString().trim();
  } catch {
    return 'unknown';
  }
}

function getGitCommitDate(): string {
  try {
    return execSync('git log -1 --format=%cI').toString().trim();
  } catch {
    return new Date().toISOString();
  }
}

function getVersion(): string {
  const pkgPath = path.resolve(rootDir, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
  return pkg.version ?? '0.0.0';
}

function getReleaseChannel(): string {
  return process.env.RELEASE_CHANNEL ?? 'dev';
}

const metadata = {
  version: getVersion(),
  commitSha: getGitCommitSha(),
  commitDate: getGitCommitDate(),
  releaseChannel: getReleaseChannel(),
};

const content = `// Auto-generated by scripts/inject-build-metadata.ts
// Do not edit manually. Run \`pnpm build:metadata\` to regenerate.

export const BUILD_METADATA = {
  version: '${metadata.version}',
  commitSha: '${metadata.commitSha}',
  commitDate: '${metadata.commitDate}',
  releaseChannel: '${metadata.releaseChannel}',
};
`;

fs.writeFileSync(generatedPath, content, 'utf-8');
console.log(`Build metadata injected: ${JSON.stringify(metadata)}`);
