// Auto-generated by scripts/inject-build-metadata.ts
// Do not edit manually. Run `pnpm build:metadata` to regenerate.

export const BUILD_METADATA = {
  version: '0.1.0-dev',
  commitSha: 'dev',
  commitDate: new Date().toISOString(),
  releaseChannel: 'dev',
};
